import timg from '@/assets/drag/timg.jpg'
import banner from '@/assets/drag/20190219184431.png'
export default [
	{
		"name":"导航模块",
		"flag":true,
		"list":[
			{
				"type":"nav",
				"style":1,
				"list":[
					{
						"icon":"/Images/images/Ico/index_icon_article.png",
						"name":"图文",
						"url":"/#/course?type=2&courseType=4"
					},
					{
						"icon":"/Images/images/Ico/index_icon_audio.png",
						"name":"音频",
						"url":"/#/course?type=2&courseType=3"
					},
					{
						"icon":"/Images/images/Ico/index_icon_live.png",
						"name":"点播",
						"url":"/#/course?type=2&courseType=1"
					},
					{
						"icon":"/Images/images/Ico/index_icon_video.png",
						"name":"直播",
						"url":"/#/course?type=1"
					},
					{
						"icon":"/Images/images/Ico/index_icon_video.png",
						"name":"专栏",
						"url":"/#/column"
					}
				]
			}
		]
	},
	{
		"name":"轮播图",
		"flag":false,
		"list":[
			{
				"type":"swiper",
				"ratio":0.56,
				"style":1,
				"list":[
					{
						"img":"/Images/images/201806/5b189d39c63a7.png"
					}
				]
			},
			{
				"type":"swiper",
				"ratio":0.42,
				"style":2,
				"list":[
					{
						"img":"/Images/images/201806/5b189d39c63a7.png"
					}
				]
			}
		]
	},
	{
		"name":"知识模块",
		"flag":false,
		"list":[
			{
				"type":"course",
				"style":1,
				"title":{
					"name":"标题",
					"more":[]
				},
				"api":{
					"act":"appCourse",
					"maxperpage": 4
				}
			},
			{
				"type":"course",
				"style":2,
				"title":{
					"name":"标题",
					"more":[]
				},
				"api":{
					"act":"appCourse",
					"maxperpage": 4
				}
			},
			{
				"type":"course",
				"style":3,
				"title":{
					"name":"标题",
					"more":[]
				},
				"api":{
					"act":"appCourse",
					"maxperpage": 4
				}
			},
			{
				"type":"class",
				"style":4,
				"title":{
					"name":"标题",
					"more":[]
				},
				"api":{
					"act":"appClass",
					"maxperpage": 4
				}
			},
			{
				"type":"course",
				"style":5,
				"title":{
					"name":"标题",
					"more":[]
				},
				"api":{
					"act":"appCourse",
					"maxperpage": 4
				}
			},
			{
				"type":"course",
				"style":6,
				"title":{
					"name":"标题",
					"more":[]
				},
				"api":{
					"act":"appCourse",
					"maxperpage": 4
				}
			},
		]
	},
	{
		"name":"老师模块",
		"flag":false,
		"list":[
			{
				"type":"teacher",
				"style":1,
				"title":{
					"name":"名师大咖",
					"more":[
						{
							"text":"查看全部",
							"url":"#/teacher"
						}
					]
				},
				"api":{
					"act":"appTeacher",
					"maxperpage": 4
				}
			}
		]
	},
	{
		"name":"新闻模块",
		"flag":false,
		"list":[
			{
				"type":"news",
				"style":1,
				"title":{
					"name":"热门头条",
					"more":[
						{
							"text":"查看更多",
							"url":"#/news"
						}
					]
				},
				"api":{
					"act":"appNews",
					"maxperpage": 4
				}
			}
		]
	},
	{
		"name":"会员卡",
		"flag":false,
		"list":[
			{
				"type":"vipcard",
				"style":1,
				"api":{
					"act":"appClubCard",
					"maxperpage": 2
				}
			},
			{
				"type":"vipcard",
				"style":2,
				"api":{
					"act":"appClubCard",
					"maxperpage": 2
				}
			}
		]
	},
	{
		"name":"广告",
		"flag":false,
		"list":[
			{
				"type":"banner",
				"src":banner,
				"url":""
			}
		]
	},
	{
		"name":"富文本",
		"flag":false,
		"list":[
			{
				"type":"richtext",
				"code":`
					<div class="md-richtext-title">课堂街，让知识变得更有价值课堂街，让知识变得更有价值</div>
					<div class="md-richtext-cont">
						<p>自从我们进入信息时代，我们跟互联网的关系是越来越密不可分，实际它已经从根本上改变了我们的生活。教育是一个人一辈子最重要的一个工程，它伴随着我们的一生也影响这我们的一生，网络早已经成为我们生存和发展的交流工具；当他们两者结合势必会带来对社会新的冲击。所以越来越多的人投入了其中。</p>
						<p><img src="${timg}" /></p>
					</div>`
			}
		]
	}
]